//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalTestWeb2.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int ID { get; set; }
        public string Courier { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Status { get; set; }
        public string ServiceType { get; set; }
        public Nullable<System.DateTime> EstShippedDate { get; set; }
        public Nullable<System.DateTime> DateOrderPlaced { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
